### ISSUE TITLE
test-map.cpp `#include "map->h"`

### ISSUE THREAD

**Issue by brycedewitt** [hurda21/cs4500-a1-part2#9]
Hey guys, not sure if we're just missing something here, but what's your reasoning behind the `#include "map->h"`?  I don't think this is needed and its messing up our tests with the Makefile from piazza

**Comment by brycedewitt** [comment]
Actually, since the testing file only includes an import for the `object.h` file (and our strings live in other separate .h files, we're using this as an empty file that just adds all the other includes.  Its kinda a hacky solution, but works for us.

If there's no reason to have it named that, I think it would just be helpful to have a `#include "map-imports.h" so that we can hook into that and add what we need.

**Comment by hurda21** [comment]
Should've been #include "map.h". Small bug from replacing all "map." to "map->".

**Comment by hurda21** [comment]
Just made the imports "object.h", "string.h". and "map.h" - would that be sufficient?

**Comment by brycedewitt** [comment]
Could you also add a few more then? Just up there to the header, in addition to the ones you already have:
#include "array.h"
#include "Boolean.h"
#include "Float.h"
#include "Integer.h"

This is just based on our implementation and would be easy enough for anyone else who did it another way to get around by just making those files empty.

**Comment by hurda21** [comment]
I see the issue - just added an empty helper.h file for those imports
